version: '3'

networks:
  node-network:
    driver: bridge

services:
  app:
    build:
      context: node
    container_name: app
    restart: always
    tty: true
    volumes:
      - ./node:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=nodedb
      - DB_PORT=3306
    ports:
      - "3000:3000"
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/db-init:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - node-network

  nginx:
    build: 
      context: nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - node-network
    depends_on: 
      - app
